---

- name: label node with cpumanager=true
  shell: oc label node {{ ansible_fqdn }} cpumanager=true --overwrite
  delegate_to: "{{ master_hostname }}"

# dont need this anymore after 3.10
#- name: enable CPUManager and HugePages feature gates on atomic-openshift-node
#  blockinfile:
#    dest: /etc/origin/node/node-config.yaml
#    backup: yes
#    state: present
#    insertafter: "DevicePlugins=true"
#    block: |2
#        - CPUManager=true
#        - HugePages=true
#        cpu-manager-policy:
#        - static
#        cpu-manager-reconcile-period:
#        - 5s
#        kube-reserved: 
#        - cpu=500m
#
#  when: inventory_hostname in groups['fast_nodes']

  #- name: restart atomic-openshift-node service to activate feature-gates
  #  systemd: name=atomic-openshift-node state=restarted

  #- name: enable HugePages feature gate on atomic-openshift-master-api
  #  blockinfile:
  #    dest: /etc/origin/master/master-config.yaml
  #    backup: yes
  #    state: present
  #    insertafter: "apiServerArguments:"
  #  block: |2
  #      - HugePages=true
  # when: inventory_hostname in groups['master']

- name: restart atomic-openshift-master-api service to activate feature-gates
  shell: master-restart controllers controllers && master-restart api api
  #  systemd: name=atomic-openshift-master-api state=restarted
  when: inventory_hostname in groups['master']

- name: write customized cpumanager-hugepages.yaml file
  template:
    src: cpumanager-hugepages.yaml.j2
    dest: /tmp/cpumanager-hugepages.yaml
  delegate_to: "{{ master_hostname }}"

- name: copy create-cpumanager-hugepages-namespace.yaml up to master
  copy:
    src: create-cpumanager-hugepages-namespace.yaml
    dest: /tmp/create-cpumanager-hugepages-namespace.yaml
  delegate_to: "{{ master_hostname }}"

- name: create cpumanager-hugepages namespace
  shell: oc create -f /tmp/create-cpumanager-hugepages-namespace.yaml
  delegate_to: "{{ master_hostname }}"

- name: create cpumanager-hugepages pod
  shell: oc create -f /tmp/cpumanager-hugepages.yaml
  delegate_to: "{{ master_hostname }}"
